# Generated by Django 5.0.8 on 2024-09-16 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitantes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitante',
            name='horario_autorizacao',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Horário de Autorização de Entrada ou Finalização'),
        ),
    ]
